// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Database;
using AppContext = WebApplication1.Database.AppContext;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20251106072004_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Database.Enteties.Stats", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("usersAmmount")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Stats");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            date = new DateTime(2025, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            usersAmmount = 37
                        },
                        new
                        {
                            id = 2L,
                            date = new DateTime(2025, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            usersAmmount = 41
                        },
                        new
                        {
                            id = 3L,
                            date = new DateTime(2025, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            usersAmmount = 24
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
