// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Database;
using AppContext = WebApplication1.Database.AppContext;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Database.Enteties.Stats", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("dau")
                        .HasColumnType("integer");

                    b.Property<int>("mau")
                        .HasColumnType("integer");

                    b.Property<int>("newUsers")
                        .HasColumnType("integer");

                    b.Property<int>("newUsersBounce")
                        .HasColumnType("integer");

                    b.Property<int>("newUsersNoBounce")
                        .HasColumnType("integer");

                    b.Property<int>("returningUsers")
                        .HasColumnType("integer");

                    b.Property<int>("returningUsersBounce")
                        .HasColumnType("integer");

                    b.Property<int>("returningUsersNoBounce")
                        .HasColumnType("integer");

                    b.Property<string>("trafficSource")
                        .HasColumnType("text");

                    b.Property<int>("visitsCount")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
